services:
  app:
    container_name: mgotow.dev
    build: .
    tty: true
    ports:
      - 3000:3000
    volumes:
      - node_modules:/app/node_modules
      - ./:/app:cached
volumes:
  node_modules: {}